[destination.postgres.credentials]
database = "media_content" # fill this in!
password = "0002" # fill this in!
username = "db_user" # fill this in!
host = "localhost" # fill this in!
port = 5432
connect_timeout = 15
